image: Visual Studio 2017
version: 1.0.0.{build}
configuration: Release
before_build:
  - dotnet restore
build:
  project: AspNetCore.TestStartup.sln
  parallel: true
  verbosity: minimal
clone_depth: 1
test_script:
- dotnet test -c Release .\test\AspNetCore.TestStartup.UnitTests\AspNetCore.TestStartup.UnitTests.csproj
after_build:
- dotnet pack .\src\AspNetCore.TestStartup\AspNetCore.TestStartup.csproj -o ../../output --no-build
artifacts:
- path: 'output\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
